name: Generator JS Docs

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Install modules
      run: npm install
    - run: npm run doc
    - name: Deploy JSDoc
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: docs # The branch the action should deploy to.
        folder: . # The folder the action should deploy.



