name: Generator JS Docs

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: npm install
    - run: npm run doc
    - name: Deploy JSDoc
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: demo/doc # The branch the action should deploy to.
        folder: . # The folder the action should deploy.



