name: Generator JS Docs

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Install modules
      run: yarn install
    - run: yarn doc
    - name: Deploy JSDoc
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: repo/demo/doc # The branch the action should deploy to.
        folder: . # The folder the action should deploy.



