name: Test Node CI

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install eslint --save-dev
    - run: npx eslint --init
    - run: eslint . --ext .js,.jsx,.ts,.tsx


