name: Deploy with JSDoc

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install modules
      run: yarn install
    - run: yarn doc
    - name: Deploy JSDoc
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: repo/feature/deploy # The branch the action should deploy to.
        folder: . # The folder the action should deploy.



