name: Lint and format then auto-commit

on: [push, pull_request]

jobs:
  eslint-prettier-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install modules
      run: yarn install
    - run: yarn lint --fix
    - name: Auto-commit formatting results
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-format to coding guidelines


