name: Test JS files

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: yarn install
    - run: sudo apt-get install xvfb

    - run: | 
        xvfb-run --auto-servernum yarn test puppet-user.test.js 
          
        

        
        


